### ISSUE TITLE
Indexing+analyzing takes too long and IDE freezes

### ISSUE THREAD

**Issue by petr-pondelik** [mesour-intellij-plugins/latte-pro-issues#69] opened 2022-10-05 14:16 UTC
**Describe the bug**
Latte files with deep structure will cause indexing and analyzing to hang.
When trying to edit such files or mark the code, the IDE freezes.

**Environment (please complete the following information):**
 - PhpStorm 2022.2.2
 - Plugin version 1.0.8

**To Reproduce**
1. Open the attached latte file as a separate project.
2. Indexing will freeze on dependencies (JAR files) or on the file itself.
3. Try to mark or edit some parts of the code. IDE will freeze for some time (~ a few minutes).
4. If you delete the file's content, indexing will finish. If you revert deleting the content, the analyzing process hangs.

**Code**
[sample.zip](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/9716356/sample.zip)

**Comment by mabar** [comment] 2022-10-05 14:18
See #68

Current solution is to split deep structures into more blocks. IntelliJ itself is quite limiting factor in this issue

**Comment by elcheco** [comment] 2022-10-13 08:59
I have the same problem in:
- 2022.3 EAP - Build #PS-223.6160.85, built on October 6, 2022
- 2022.2.3

Indexing takes forever - probably several hours - I just a few times noticed that it finished when I let my computer open for a few hours or overnight... Almost impossible to work properly. We have several modules - I needed to mark some of the module directories as excluded to be able to at least work...

**Comment by mabar** [comment] 2022-10-17 19:35
Probably unrelated, but you may try to exclude directory with your project in antivirus and also disable all other plugins, to be sure Latte plugin is the root cause of your issues. My antivirus made tens of seconds long indexing into several hours...

**Comment by elcheco** [comment] 2022-10-25 14:58
I am on Mac - no antivirus. Today I got into a situation where Latte Pro blocks indexing - as I said forever - for hours on the 2022.2.3 version. So basically nothing is working. I invalidate caches several times and always the same - one hour or even more "indexing". Today it never ended as my patience was gone. I remember it ended overnight, but then I upstream from the master and started indexing again...

Finally, I uninstalled Latte Pro, I installed Latte - indexing took 2 minutes and everything is working. So obviously is something wrong with the plugin. The question is what and if I should pay it when it basically doesn't allow me to work normally... I purchased even 4 licenses for the team and all have similar issues...

**Comment by elcheco** [comment] 2022-11-21 09:52
Ok, no progress, no care...
I just canceled four company licenses as all of us have on Mac the same issue, never-ending indexing, which basically won't let us work... 
It's not a one-user issue...

**Comment by mesour** [comment] 2022-12-08 18:29
@elcheco @petr-pondelik I have some ideas, how to improve plugin performance, but now I have no time for plugin development. I will have time at the end of December.

@elcheco recommendation for now is (as @mabar said) not have deep structures and not use unpaired `{label ...}` tag without `/}` on end (use only `{label ...}{/label}` or `{label ... /}`. In 90% label tag caused this problems with performance.

> Latte in newest version also recommend use unpaired label with `/}` at the end: https://doc.nette.org/en/forms/rendering#toc-latte. Maybe it will also trigger warning while compilate template.

**Comment by Rashengka** [comment] 2023-02-01 11:22
@mesour Just bought your latte pro plugin to work on my main project (10 years in development) and indexing never ends, so I was wondering if you will fix this any time soon of if I should ask for refund. Thx.

**Comment by mesour** [comment] 2023-02-01 18:28
@Rashengka For me everything working fine in my PHP projects. Have you tried the things described in this issue? Now I have no time to develop plugins.

**Comment by Rashengka** [comment] 2023-02-01 18:59
@mesour I had my colleague test it, same problem on his mac.
As i previously mentioned, project i work on is old an very very large, with hundreds of latte files, so splitting is not solution because there is no way to find which files are problemous.

It would be very cool if your plugin did not block indexing - it makes storm useful as notepad.
Well please fix it soon, your plugin licence was not exactly cheap.

**Comment by elcheco** [comment] 2023-02-01 22:13
@mesour @Rashengka 

We have three projects running on Nette in the company. I bought four business licenses for our team, even though it was almost twice more expensive as, for example, Laravel Idea. It was killing PHP Storm on indexing to all of us on all projects!!!

The only support here was to make it simple. Sorry, we're not making a blog, but a serious business, quite a large application, and to have one latte file with thousands of lines is going against the principles of many principles of programming. 

It even cost me some reputation as I decided to go for Nette in Germany, where literally nobody knows it. It's not a problem of Nette itself, works perfectly fine, but it puts some questions and doubt in my colleagues. I instructed them to install the licensed plugin, and after three days, I had to tell them to take it away and go back to the classic Latte plugin.

**Comment by mabar** [comment] 2023-02-02 02:07
> It would be very cool if your plugin did not block indexing

@mesour Could we make indexing of a file timeout? Just ignore the file if indexing takes too much time

> one latte file with thousands of lines is going against the principles

That's the exact type of files that plugin does not like currently

@Rashengka @elcheco Sorry to hear about your issues. So far we know that issue may be related to these things (or their combinations)
- MacOS (are you running on M1/2 chips or older?)
- Huge files (thousands of lines)
- Deep nesting of elements instead of using {block} or multiple files
- pair {label foo} without closing tag (invalid since Latte 3)
- varType/templateType/var type definitions are missing and plugin has to guess variable types
- maybe css styles and js literals because they match latte syntax and plugin is not yet able to differentiate between them

If you could try to find files which freeze the indexing and post them, it would be really helpful for finding root cause of the issue. It's bit unconvenient trial-error debugging loading just part of the project until the broken file is found, but it is doable.

@mesour I tried the file from @petr-pondelik and it seems to index fine, but editing is still a nightmare. I think plugin could try to revalidate only nodes related to the change:
- adding/removing lines is fine anywhere
- editing node should only affect current node (and inner ones if latte part of the template is changed)
- moving node should only affect blocks which are being changed (maybe with a delay like 0.1s after last change)

Sorry again for the issues folks. Most common indexing issues were already fixed but we really need issue samples to identify the more specific errors.

**Comment by Rashengka** [comment] 2023-02-02 07:16
@mesour 
I am running Apple M1, latest OS version, PHPStorm v.2022.3.2

Attached file is latte on which is indexing stucked right now for some minutes.
[list.latte.zip](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10566116/list.latte.zip)

Storm showed me this exception right after opening, no idea if it is related to indexing, also attached as file.
[com.intellij.diagnostic.PluginException.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10566134/com.intellij.diagnostic.PluginException.txt)

edit: after few hours still indexing same file (list.latte)

**Comment by elcheco** [comment] 2023-02-02 09:48
> @elcheco @petr-pondelik I have some ideas how to improve plugin performance, but now I have no time for plugin development. I will have time at the end of December.
> 
> @elcheco recommendation for now is (as @mabar said) not to have deep structures and not use unpaired `{label ...}` tag without `/}` on end (use only `{label ...}{/label}` or `{label ... /}`. In 90% label tag caused this problems with performance.
> 
> > Latte in newest version also recommend use unpaired label with `/}` at the end: https://doc.nette.org/en/forms/rendering#toc-latte. Maybe it will also trigger warning while compilate template.

@mesour @mabar 
I decided to test the latest two January versions. I bought the personal license, and I see the same problem. It's again indexing forever. 

We are on M1 Pro Macs with 32GB RAM, but issued had also colleagues on Intel Macs. Latest OS . Now Ventura, before it was Monterey. Currently on PHPStorm 2022.3.2. I might try even 2023.1 EAP if it makes sense...

We don't use any {label} tags at all. We use the n:tags like n:name for forms.

What about other unpaired tags? Translation {_'text'}? Custom unpaired tags? I specified the custom ones in the intellij-latte.pro file, but no change...

Deep structure? We have a template for action, and we usually {include} some other files which can be used in multiple templates. {block} we use mainly on layout files, but at some action templates too.

**Comment by mesour** [comment] 2023-02-02 11:49
@Rashengka I added your file to my project. Here is no error in this file. I initiate invalidate cache for indexes. Everything is indexed and working fine as expected. So I can not reproduce problem with your file.

**Comment by Rashengka** [comment] 2023-02-02 11:50
@mesour 
found good example of Storm killer, just extract and rename ext to .latte
[some_old_email_template.latte.html.zip](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10568587/some_old_email_template.latte.html.zip)

this will kill storm even if project contains only this file

**Comment by Rashengka** [comment] 2023-02-02 11:52
> @Rashengka I added your file to my project. Here is no error in this file. I initiate invalidate cache for indexes. Everything is indexed and working fine as expected. So I can not reproduce problem with your file.

After I added {varType, problem jumped to other file. 
edit: varType fixed list.latte

**Comment by mesour** [comment] 2023-02-02 11:54
@Rashengka Now I think of one thing I can try to fix. It will be in the next version during February. But I don't know if it will work, it's like shooting blindly. I can only speculate as to what is causing the problem.

**Comment by Rashengka** [comment] 2023-02-02 12:36
@mesour try to take one block (first top lvl table named Paragraph) from [some_old_email_template.latte.html.zip](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10568587/some_old_email_template.latte.html.zip) maybe it might be helpful if as it blocks indexing without killing storm

**Comment by Rashengka** [comment] 2023-03-09 07:35
@mesour any news on fix?

**Comment by Rashengka** [comment] 2023-03-21 08:41
> @mesour any news on fix?

@mesour not even any reply at all?

**Comment by mesour** [comment] 2023-04-05 15:58
@Rashengka in `1.0.11` is something, what can fix this problem. This version will be available for download in 2 days.

**Comment by mesour** [comment] 2023-04-06 15:24
Try it and if problem persist, feel free to comment and/or reopen issue

**Closed as completed by mesour** 2023-04-06 15:24 UTC
Labels: bug, next version candidate
